// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {cpolar} from '../models';

export function AddTunnel(arg1:string,arg2:string):Promise<void>;

export function DeleteConfigFile():Promise<void>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function Generate():Promise<main.UserInfo>;

export function GenerateTunnel():Promise<cpolar.User>;

export function GetId():Promise<string>;

export function Start():Promise<void>;

export function Stop():Promise<void>;
