// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTunnel(arg1, arg2) {
  return window['go']['main']['App']['AddTunnel'](arg1, arg2);
}

export function DeleteConfigFile() {
  return window['go']['main']['App']['DeleteConfigFile']();
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function Generate() {
  return window['go']['main']['App']['Generate']();
}

export function GenerateTunnel() {
  return window['go']['main']['App']['GenerateTunnel']();
}

export function GetId() {
  return window['go']['main']['App']['GetId']();
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
