// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Generate():Promise<main.UserInfo>;

export function GetId():Promise<string>;

export function Start():Promise<void>;
